#!/bin/sh -e
echo "Install the multiple process stack: runit, syslog-ng-core, logrotate and cron"
/container/tool/add-service-available _runit _syslog-ng-core _logrotate _cron
touch /container/multiple_process_stack_added
